services:

  app:
    build: .
    env_file: .env
    environment:
      FLASK_SQLALCHEMY_DATABASE_URI: "postgresql+pg8000://schemes:password@database/schemes"
      FLASK_CAPITAL_SCHEMES_DATABASE_URI: "postgresql+pg8000://ate:password@database:5433/capital-schemes"
    networks:
      - schemes-network
    ports:
      - "5000:5000"
    depends_on:
      database:
        condition: service_healthy

  database:
    image: postgres:16
    environment:
      POSTGRES_USER: schemes
      POSTGRES_PASSWORD: password
    networks:
      - schemes-network
    ports:
      - "5432:5432"
    healthcheck:
      test: pg_isready -U $$POSTGRES_USER
      interval: 5s

networks:
  schemes-network:
    external: true
