name: 'Deploy Dev'

on:
  workflow_call:

jobs:

  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS_DEPLOY_DEV }}'

      - name: Deploy image
        uses: google-github-actions/deploy-cloudrun@v1
        with:
          service: schemes
          image: europe-west1-docker.pkg.dev/dft-schemes-common/docker/schemes
          region: europe-west1
